### PR TITLE
OrtValue shared pointer thread safety - 172

### PR DESCRIPTION
**Pull request by mrodozov**
it's a copy of #5 on 1.7.2

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
if it builds we can test for specific workflows on Arm to check it

**Comment by dan131riley** [comment]
Apparently not a complete fix, I'm still getting
```
  what():  /tmp/dsr/onnxruntime/onnxruntime/core/framework/bfc_arena.cc:472 void onnxruntime::BFCArena::RemoveFreeChunkFromBin(onnxruntime::BFCArena::ChunkHandle) !c->in_use() && (c->bin_num != kInvalidBinNum) was false. 
```
but I think it's worth going ahead to see if this reduces the frequency substantially.

**Comment by mrodozov** [comment]
I'm testing it for Arm and I'll merge it

**Comment by mrodozov** [comment]
please test for slc7_aarch64_gcc9

**Comment by mrodozov** [comment]
please test for slc7_ppc64le_gcc9

**Comment by mrodozov** [comment]
without an error on arm . havent seen this in a while :) I'm merging this

**Pull request merged**
